### ISSUE TITLE
Protexiom - forme adresse url somfy

### ISSUE THREAD

**Issue by ericfra** [Pschittt/HASS-Somfy-Protexiom#1]
Bonjour,
sous quelle forme faut il rentrer l'adresse url de la centrale protexiom ? 
Est ce correct comme ca ? Faut il entrer "Utilisateur1" quelque part ?
En plus je suis sur un port particulier 2330

protexiom:
  url: http://192.168.1.222:2330
  password: 1234
  codes:
     key_A1: 0000
etc.....

Si ca marche sur ma Protexiom 400 ce serait super

Merci pour le dev

**Comment by Pschittt** [comment]
Pensez bien aux tabulations comme décris dans le Readme, ou en page de présentation sur le git.

**Comment by ericfra** [comment]
J'ai bien respecté la tabulation avec SublimeText pour éditeur:
protexiom: et ca ne fonctionne pas,

-------------------------
protexiom:
  url: http://192.168.1.222:2330
  password: 1234
  codes:
    key_A1: 2829
    key_A2: 3131
-----------------------------
J'ai en notification:
Component error: protexiom - Integration 'protexiom' not found.
15:38:06 – Hass.io (ERROR)
Error loading custom_components.protexiom. Make sure all dependencies are installed
15:38:06 – custom_components/protexiom/somfy.py (ERROR)

qu'en pensez vous?
merci :)

**Comment by Pschittt** [comment]
J’ai l’impression qu’à l’initialisation Hass n’installe pas les dépendances.

Pourriez-vous activer le mode débug du composant dans le fichier de conf de HASS ?

```
logger:
  logs:
    custom_components.protexiom: debug
```

**Comment by ericfra** [comment]
le fichier est très gros quelles lignes vous faut il ?

**Comment by Pschittt** [comment]
Ne m'envoyez surtout pas tout le fichier.
Lorsque le mode debug est activé pour ce custom component, j'affiche les codes et autres dans les logs. Ca me permettait de faciliter le debug.

Donc regardez le fichier, et essayez de fournir les lignes en erreur. Vu que vous n'arrivez pas à le lancer, cela devrait être en début (~50 premières lignes je dirai).

**Comment by adidoo** [comment]
Bonjour,

J'ai le même problème que précédemment je pense. En fait c'est le module Mechanize qu'il ne trouve pas. Je ne connais pas très bien encore comment fonctionne les composants sur home assistant et comment on peut ajouter un module. Pour info, je suis sur hassos : 

`Détails du journal ( ERROR )
Logger: homeassistant.loader
Source: custom_components/protexiom/somfy.py:3
First occurred: 22:07:22 (1 occurrences)
Last logged: 22:07:22

Error loading custom_components.protexiom. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 436, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/protexiom/__init__.py", line 2, in <module>
    from .somfy import Somfy
  File "/config/custom_components/protexiom/somfy.py", line 3, in <module>
    import mechanize
ModuleNotFoundError: No module named 'mechanize'`


Merci d'avance

**Comment by Pschittt** [comment]
Je confirme, il manque bien mechanize. Pourtant HA est censé l'installer à l'initialisation du composant, vu qu'il est spécifié dans le fichier manifest.

Essayez d'installer mechanize à la main :
`pip3 install mechanize`

**Comment by adidoo** [comment]
Le problème est que dans hassos (L'image fournie par Hass.io), il n'y a pas pip et autres commandes avancées. 
Seulement les commandes Busybox.
En cherchant, j'ai l'impression que mechanize n'existe pas pour python 3 (https://github.com/MechanicalSoup/MechanicalSoup). Le problème n'est pas arrivé avec un changement de version de Python dans Hassos ? Qui pourrait ne pas exister quand on installe home assistant core sur une distribution existante ?
