### ISSUE TITLE
Cannot log in 

### ISSUE THREAD

**Issue by jibito** [Pschittt/HASS-Somfy-Protexiom#3]
Bonjour, 

J'ai bien configurer le plugin comme décrit dans la description. 
Mais malheureusement, un message apparait ""

Voici l'extrait de log : 

![error](https://user-images.githubusercontent.com/31941171/83366477-a3be8d80-a3af-11ea-8e9b-d9d167a6137e.PNG)

Pouvez-vous m'aider svp ? 

Merci d'avance. 

Bien Cordialement,

**Comment by Pschittt** [comment]
Bonjour,

Quelle est la version de votre alarme protexiom ? Et quelle année ?

**Comment by jibito** [comment]
Bonjour, 

Il me semble que c'est un modèle Protexiom 5000, année 2019-2010. (Ce n'est pas la mienne mais celle de mes parents). 

Sinon, j'ai jeter un oeil au script, j'ai modifié quelques éléments : 

--- Somfy.py 

- L'URL de la page web de login est de la forme : http://mon-ip/fr/login.htm.
J'ai donc modifié cela dans le script, ainsi que l'affectation : 
authentication_code = login_soup.find('form').find('table').findAll('tr')[2].findAll('b')[0].find(text=True) <== j'obtenais une erreur "Index of range"

et je suis arrivé à me logger 

- Ensuite, il n'y a pas de page "etat.htm", ni "u_etat.htm" ni autre chose de ce genre, j'ai donc commenter la fonction "get_state"

- La page, "u_pilotage.htm" existe bien donc j'ai laissé tel quel. 


Pour conclure, les éléments sont bien remontés ds Home-Assistant, mais je n'obtiens pas d'état. 
Je ne peux aussi pas armer et désarmer l'alarme. 

Pouvez-vous m'aider à l'adapter ? 
Je suis prêt à vous aider si besoin est. 

Merci d'avance en tout cas.

**Comment by Pschittt** [comment]
Duplicate of #2

**Comment by Pschittt** [comment]
Je vous invite à aller voir l’autre issue 
Duplicate of #2
