### ISSUE TITLE
Rendre le repository compatible HACS

### ISSUE THREAD

**Issue by lavaredo** [Pschittt/HASS-Somfy-Protexiom#6]
Bonjour,
tout d'abord merci pour ton travail.
Serait-il possible de rendre ton repository compatible avec les guidelines de HACS, afin de faciliter l'installation et la mise à jour ? Et plus généralement, rendre l'intégration un peu plus user-friendly, pour les utilisateurs néophytes comme moi, avec un petit menu où mettre les paramètres, et tout le toutim déjà bien paramétré pour éviter le YAML ? Ce serait vraiment super ! :-)
Je te remercie.

**Comment by Pschittt** [comment]
Merci pour la/les suggestions.

J'ai pas du tout le temps de le faire évoluer. J'ai essayé de faire un readme le plus détaillé possible.

Si une personne veut fork le projet et l'améliorer, il ne faut pas hésiter :)
